name: CI

on:
  push:
    branches: [master]
  pull_request:
    types:
      - opened
      - synchronize


jobs:
  test:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - run: sleep 60 && echo "OK"
